[app]
overall = { bg = "#2d3833" }

[mgr]
cwd = { fg = "#9bb5b1" }

find_keyword  = { fg = "#d6caa3", italic = true }
find_position = { fg = "#caacc2", bg = "reset", italic = true }

marker_copied   = { fg = "#a8b59b", bg = "#a8b59b" }
marker_cut      = { fg = "#d99c82", bg = "#d99c82" }
marker_marked   = { fg = "#9bb5b1", bg = "#9bb5b1" }
marker_selected = { fg = "#8da7b3", bg = "#8da7b3" }

count_copied   = { fg = "#2d3833", bg = "#a8b59b" }
count_cut      = { fg = "#2d3833", bg = "#d99c82" }
count_selected = { fg = "#2d3833", bg = "#8da7b3" }

border_symbol = "│"
border_style  = { fg = "#677a70" }

syntect_theme = "~/.config/yazi/Sagewood.tmTheme"

[tabs]
active   = { fg = "#2d3833", bg = "#d2ded7", bold = true }
inactive = { fg = "#d2ded7", bg = "#3b4a43" }

[mode]
normal_main = { fg = "#2d3833", bg = "#8da7b3", bold = true }
normal_alt  = { fg = "#8da7b3", bg = "#222a26"}

select_main = { fg = "#2d3833", bg = "#a8b59b", bold = true }
select_alt  = { fg = "#a8b59b", bg = "#222a26"}

unset_main  = { fg = "#2d3833", bg = "#9bb5b1", bold = true }
unset_alt   = { fg = "#9bb5b1", bg = "#222a26"}

[indicator]
parent = { fg = "#2d3833", bg = "#d2ded7" }
current = { fg = "#2d3833", bg = "#8da7b3" }
preview = { fg = "#2d3833", bg = "#d2ded7" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#d2ded7", bold = true }
progress_normal = { fg = "#a8b59b", bg = "#3b4a43" }
progress_error  = { fg = "#d6caa3", bg = "#d99c82" }

perm_type  = { fg = "#8da7b3" }
perm_read  = { fg = "#d6caa3" }
perm_write = { fg = "#d99c82" }
perm_exec  = { fg = "#a8b59b" }
perm_sep   = { fg = "#677a70" }

[input]
border   = { fg = "#8da7b3" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#8da7b3" }
active   = { fg = "#caacc2" }
inactive = {}

[confirm]
border     = { fg = "#8da7b3" }
title      = { fg = "#8da7b3" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#8da7b3" }

[tasks]
border  = { fg = "#8da7b3" }
title   = {}
hovered = { fg = "#caacc2", bold = true }

[which]
mask            = { bg = "#222a26" }
cand            = { fg = "#9bb5b1" }
rest            = { fg = "#677a70" }
desc            = { fg = "#caacc2" }
separator       = "  "
separator_style = { fg = "#3b4a43" }

[help]
on      = { fg = "#9bb5b1" }
run     = { fg = "#caacc2" }
desc    = { fg = "#677a70" }
hovered = { bg = "#3b4a43", bold = true }
footer  = { fg = "#d2ded7", bg = "#3b4a43" }

[notify]
title_info  = { fg = "#9bb5b1" }
title_warn  = { fg = "#d6caa3" }
title_error = { fg = "#d99c82" }

[filetype]
rules = [
	{ mime = "image/*", fg = "#d6caa3" },
	{ mime = "{audio,video}/*", fg = "#caacc2" },

	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d99c82" },

	{ mime = "application/{pdf,doc,rtf}", fg = "#9bb5b1" },

	{ mime = "vfs/{absent,stale}", fg = "#3b4a43" },

	{ url = "*", is = "orphan", bg = "#d99c82" },
	{ url = "*", is = "exec"  , fg = "#a8b59b" },

	{ url = "*", is = "dummy", bg = "#d99c82" },
	{ url = "*/", is = "dummy", bg = "#d99c82" },

	{ url = "*/", fg = "#8da7b3" },
]

[spot]
border = { fg = "#8da7b3" }
title  = { fg = "#8da7b3" }
tbl_cell = { fg = "#8da7b3", reversed = true }
tbl_col = { bold = true }
