set -g status-justify left
set -g status-style "bg=#2d3833,fg=#d2ded7"
set -g status-left ""
set -g status-left-length 0
set -g status-right ""
set -g status-right-length 0
setw -g window-status-format "#[fg=#677a70,bg=#2d3833] #I:#W "
setw -g window-status-current-format "#[fg=#d2ded7,bg=#3b4a43,bold] #I:#W "
set -g pane-border-style "fg=#222a26"
set -g pane-active-border-style "fg=#3b4a43"
